name: CI

# For testing
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
  
      # Build all the packages
      - name: Create packages for TSConfig JSONs
        run: deno run --allow-read --allow-write --allow-net scripts/create-npm-packages.ts

      - name: Update the README
        run: deno run --allow-read --allow-write --allow-net scripts/update-markdown-readme.ts
      
      - name: Fail if the README needs updating
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo ""
          else
            echo "Please update the README via: deno run --allow-read --allow-write scripts/update-markdown-readme.ts"
            exit 1
          fi